//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.23 at 12:08:40 PM EST 
//


package com.demo.domain;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.demo.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.demo.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WriteEventLog }
     * 
     */
    public WriteEventLog createWriteEventLog() {
        return new WriteEventLog();
    }

    /**
     * Create an instance of {@link WriteEventLogRequest }
     * 
     */
    public WriteEventLogRequest createWriteEventLogRequest() {
        return new WriteEventLogRequest();
    }

    /**
     * Create an instance of {@link WriteEventLogResponse }
     * 
     */
    public WriteEventLogResponse createWriteEventLogResponse() {
        return new WriteEventLogResponse();
    }

    /**
     * Create an instance of {@link Notification }
     * 
     */
    public Notification createNotification() {
        return new Notification();
    }

    /**
     * Create an instance of {@link TransactionDetail }
     * 
     */
    public TransactionDetail createTransactionDetail() {
        return new TransactionDetail();
    }

    /**
     * Create an instance of {@link VersionId }
     * 
     */
    public VersionId createVersionId() {
        return new VersionId();
    }

    /**
     * Create an instance of {@link CompletedTrackDetail }
     * 
     */
    public CompletedTrackDetail createCompletedTrackDetail() {
        return new CompletedTrackDetail();
    }

    /**
     * Create an instance of {@link TrackSplitShipmentPart }
     * 
     */
    public TrackSplitShipmentPart createTrackSplitShipmentPart() {
        return new TrackSplitShipmentPart();
    }

    /**
     * Create an instance of {@link CustomerExceptionRequestDetail }
     * 
     */
    public CustomerExceptionRequestDetail createCustomerExceptionRequestDetail() {
        return new CustomerExceptionRequestDetail();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link TrackPayment }
     * 
     */
    public TrackPayment createTrackPayment() {
        return new TrackPayment();
    }

    /**
     * Create an instance of {@link DeliveryOptionEligibilityDetail }
     * 
     */
    public DeliveryOptionEligibilityDetail createDeliveryOptionEligibilityDetail() {
        return new DeliveryOptionEligibilityDetail();
    }

    /**
     * Create an instance of {@link ContentRecord }
     * 
     */
    public ContentRecord createContentRecord() {
        return new ContentRecord();
    }

    /**
     * Create an instance of {@link TrackDetail }
     * 
     */
    public TrackDetail createTrackDetail() {
        return new TrackDetail();
    }

    /**
     * Create an instance of {@link Measure }
     * 
     */
    public Measure createMeasure() {
        return new Measure();
    }

    /**
     * Create an instance of {@link Distance }
     * 
     */
    public Distance createDistance() {
        return new Distance();
    }

    /**
     * Create an instance of {@link EdtExciseCondition }
     * 
     */
    public EdtExciseCondition createEdtExciseCondition() {
        return new EdtExciseCondition();
    }

    /**
     * Create an instance of {@link AppointmentTimeDetail }
     * 
     */
    public AppointmentTimeDetail createAppointmentTimeDetail() {
        return new AppointmentTimeDetail();
    }

    /**
     * Create an instance of {@link TrackEvent }
     * 
     */
    public TrackEvent createTrackEvent() {
        return new TrackEvent();
    }

    /**
     * Create an instance of {@link TrackInformationNoteDetail }
     * 
     */
    public TrackInformationNoteDetail createTrackInformationNoteDetail() {
        return new TrackInformationNoteDetail();
    }

    /**
     * Create an instance of {@link TrackSpecialInstruction }
     * 
     */
    public TrackSpecialInstruction createTrackSpecialInstruction() {
        return new TrackSpecialInstruction();
    }

    /**
     * Create an instance of {@link TrackServiceDescriptionDetail }
     * 
     */
    public TrackServiceDescriptionDetail createTrackServiceDescriptionDetail() {
        return new TrackServiceDescriptionDetail();
    }

    /**
     * Create an instance of {@link Weight }
     * 
     */
    public Weight createWeight() {
        return new Weight();
    }

    /**
     * Create an instance of {@link LocalTimeRange }
     * 
     */
    public LocalTimeRange createLocalTimeRange() {
        return new LocalTimeRange();
    }

    /**
     * Create an instance of {@link TrackStatusDetail }
     * 
     */
    public TrackStatusDetail createTrackStatusDetail() {
        return new TrackStatusDetail();
    }

    /**
     * Create an instance of {@link TrackAdvanceNotificationDetail }
     * 
     */
    public TrackAdvanceNotificationDetail createTrackAdvanceNotificationDetail() {
        return new TrackAdvanceNotificationDetail();
    }

    /**
     * Create an instance of {@link TrackChargeDetail }
     * 
     */
    public TrackChargeDetail createTrackChargeDetail() {
        return new TrackChargeDetail();
    }

    /**
     * Create an instance of {@link TrackReconciliation }
     * 
     */
    public TrackReconciliation createTrackReconciliation() {
        return new TrackReconciliation();
    }

    /**
     * Create an instance of {@link NotificationParameter }
     * 
     */
    public NotificationParameter createNotificationParameter() {
        return new NotificationParameter();
    }

    /**
     * Create an instance of {@link StringBarcode }
     * 
     */
    public StringBarcode createStringBarcode() {
        return new StringBarcode();
    }

    /**
     * Create an instance of {@link SpecialInstructionStatusDetail }
     * 
     */
    public SpecialInstructionStatusDetail createSpecialInstructionStatusDetail() {
        return new SpecialInstructionStatusDetail();
    }

    /**
     * Create an instance of {@link AppointmentDetail }
     * 
     */
    public AppointmentDetail createAppointmentDetail() {
        return new AppointmentDetail();
    }

    /**
     * Create an instance of {@link TrackOtherIdentifierDetail }
     * 
     */
    public TrackOtherIdentifierDetail createTrackOtherIdentifierDetail() {
        return new TrackOtherIdentifierDetail();
    }

    /**
     * Create an instance of {@link AvailableImagesDetail }
     * 
     */
    public AvailableImagesDetail createAvailableImagesDetail() {
        return new AvailableImagesDetail();
    }

    /**
     * Create an instance of {@link NaftaCommodityDetail }
     * 
     */
    public NaftaCommodityDetail createNaftaCommodityDetail() {
        return new NaftaCommodityDetail();
    }

    /**
     * Create an instance of {@link Money }
     * 
     */
    public Money createMoney() {
        return new Money();
    }

    /**
     * Create an instance of {@link DateRange }
     * 
     */
    public DateRange createDateRange() {
        return new DateRange();
    }

    /**
     * Create an instance of {@link Commodity }
     * 
     */
    public Commodity createCommodity() {
        return new Commodity();
    }

    /**
     * Create an instance of {@link Localization }
     * 
     */
    public Localization createLocalization() {
        return new Localization();
    }

    /**
     * Create an instance of {@link TrackSpecialHandling }
     * 
     */
    public TrackSpecialHandling createTrackSpecialHandling() {
        return new TrackSpecialHandling();
    }

    /**
     * Create an instance of {@link TrackReturnDetail }
     * 
     */
    public TrackReturnDetail createTrackReturnDetail() {
        return new TrackReturnDetail();
    }

    /**
     * Create an instance of {@link Dimensions }
     * 
     */
    public Dimensions createDimensions() {
        return new Dimensions();
    }

    /**
     * Create an instance of {@link TrackingDateOrTimestamp }
     * 
     */
    public TrackingDateOrTimestamp createTrackingDateOrTimestamp() {
        return new TrackingDateOrTimestamp();
    }

    /**
     * Create an instance of {@link PieceCountVerificationDetail }
     * 
     */
    public PieceCountVerificationDetail createPieceCountVerificationDetail() {
        return new PieceCountVerificationDetail();
    }

    /**
     * Create an instance of {@link TrackPackageIdentifier }
     * 
     */
    public TrackPackageIdentifier createTrackPackageIdentifier() {
        return new TrackPackageIdentifier();
    }

    /**
     * Create an instance of {@link Contact }
     * 
     */
    public Contact createContact() {
        return new Contact();
    }

    /**
     * Create an instance of {@link CustomsOptionDetail }
     * 
     */
    public CustomsOptionDetail createCustomsOptionDetail() {
        return new CustomsOptionDetail();
    }

    /**
     * Create an instance of {@link ContactAndAddress }
     * 
     */
    public ContactAndAddress createContactAndAddress() {
        return new ContactAndAddress();
    }

    /**
     * Create an instance of {@link SignatureImageDetail }
     * 
     */
    public SignatureImageDetail createSignatureImageDetail() {
        return new SignatureImageDetail();
    }

    /**
     * Create an instance of {@link TrackStatusAncillaryDetail }
     * 
     */
    public TrackStatusAncillaryDetail createTrackStatusAncillaryDetail() {
        return new TrackStatusAncillaryDetail();
    }

}
