
package com.demo.domain;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TrackPortType", targetNamespace = "http://demo.com/ws/track/v12")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TrackPortType {


    /**
     * 
     * @param request
     * @return
     *     returns com.demo.ws.track.v12.WriteEventLogReturn
     */
    @WebMethod(action = "http://demo.com/ws/track/v12")
    @WebResult(name = "response", targetNamespace = "http://demo.com/ws/track/v12")
    @RequestWrapper(localName = "writeEventLog", targetNamespace = "http://demo.com/ws/track/v12", className = "com.demo.ws.track.v12.WriteEventLog")
    @ResponseWrapper(localName = "writeEventLogResponse", targetNamespace = "http://demo.com/ws/track/v12", className = "com.demo.ws.track.v12.WriteEventLogResponse")
    public WriteEventLogReturn writeEventLog(
        @WebParam(name = "request", targetNamespace = "http://demo.com/ws/track/v12")
        WriteEventLogRequest request);

}
