//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.24 at 12:24:50 PM EST 
//


package com.demo.swatchdaylight.reach4mobile;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.demo.swatchdaylight.reach4mobile package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.demo.swatchdaylight.reach4mobile
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateRma }
     * 
     */
    public CreateRma createCreateRma() {
        return new CreateRma();
    }

    /**
     * Create an instance of {@link CtModestoWsaWsCreateRmaRequest }
     * 
     */
    public CtModestoWsaWsCreateRmaRequest createCtModestoWsaWsCreateRmaRequest() {
        return new CtModestoWsaWsCreateRmaRequest();
    }

    /**
     * Create an instance of {@link AssignSnAndActivate }
     * 
     */
    public AssignSnAndActivate createAssignSnAndActivate() {
        return new AssignSnAndActivate();
    }

    /**
     * Create an instance of {@link CtModestoWsaWsAssignSnAndActivateRequest }
     * 
     */
    public CtModestoWsaWsAssignSnAndActivateRequest createCtModestoWsaWsAssignSnAndActivateRequest() {
        return new CtModestoWsaWsAssignSnAndActivateRequest();
    }

    /**
     * Create an instance of {@link SetSnsAndTracking }
     * 
     */
    public SetSnsAndTracking createSetSnsAndTracking() {
        return new SetSnsAndTracking();
    }

    /**
     * Create an instance of {@link CtModestoWsaWsSetSnsAndTrackingRequest }
     * 
     */
    public CtModestoWsaWsSetSnsAndTrackingRequest createCtModestoWsaWsSetSnsAndTrackingRequest() {
        return new CtModestoWsaWsSetSnsAndTrackingRequest();
    }

    /**
     * Create an instance of {@link SetSnsAndTrackingResponse }
     * 
     */
    public SetSnsAndTrackingResponse createSetSnsAndTrackingResponse() {
        return new SetSnsAndTrackingResponse();
    }

    /**
     * Create an instance of {@link CtModestoWsaWsSetSnsAndTrackingResponse }
     * 
     */
    public CtModestoWsaWsSetSnsAndTrackingResponse createCtModestoWsaWsSetSnsAndTrackingResponse() {
        return new CtModestoWsaWsSetSnsAndTrackingResponse();
    }

    /**
     * Create an instance of {@link CancelOrderResponse }
     * 
     */
    public CancelOrderResponse createCancelOrderResponse() {
        return new CancelOrderResponse();
    }

    /**
     * Create an instance of {@link CtModestoWsaWsCancelOrderResponse }
     * 
     */
    public CtModestoWsaWsCancelOrderResponse createCtModestoWsaWsCancelOrderResponse() {
        return new CtModestoWsaWsCancelOrderResponse();
    }

    /**
     * Create an instance of {@link CancelOrder }
     * 
     */
    public CancelOrder createCancelOrder() {
        return new CancelOrder();
    }

    /**
     * Create an instance of {@link CtModestoWsaWsCancelOrderRequest }
     * 
     */
    public CtModestoWsaWsCancelOrderRequest createCtModestoWsaWsCancelOrderRequest() {
        return new CtModestoWsaWsCancelOrderRequest();
    }

    /**
     * Create an instance of {@link DeactivateDevice }
     * 
     */
    public DeactivateDevice createDeactivateDevice() {
        return new DeactivateDevice();
    }

    /**
     * Create an instance of {@link CtModestoWsaWsDeactivateDeviceRequest }
     * 
     */
    public CtModestoWsaWsDeactivateDeviceRequest createCtModestoWsaWsDeactivateDeviceRequest() {
        return new CtModestoWsaWsDeactivateDeviceRequest();
    }

    /**
     * Create an instance of {@link AssignSnAndActivateResponse }
     * 
     */
    public AssignSnAndActivateResponse createAssignSnAndActivateResponse() {
        return new AssignSnAndActivateResponse();
    }

    /**
     * Create an instance of {@link CtModestoWsaWsAssignSnAndActivateResponse }
     * 
     */
    public CtModestoWsaWsAssignSnAndActivateResponse createCtModestoWsaWsAssignSnAndActivateResponse() {
        return new CtModestoWsaWsAssignSnAndActivateResponse();
    }

    /**
     * Create an instance of {@link WriteEventLog }
     * 
     */
    public WriteEventLog createWriteEventLog() {
        return new WriteEventLog();
    }

    /**
     * Create an instance of {@link CtModestoWsaWsWriteEventLogRequest }
     * 
     */
    public CtModestoWsaWsWriteEventLogRequest createCtModestoWsaWsWriteEventLogRequest() {
        return new CtModestoWsaWsWriteEventLogRequest();
    }

    /**
     * Create an instance of {@link Exception }
     * 
     */
    public Exception createException() {
        return new Exception();
    }

    /**
     * Create an instance of {@link AbstractException }
     * 
     */
    public AbstractException createAbstractException() {
        return new AbstractException();
    }

    /**
     * Create an instance of {@link WriteEventLogResponse }
     * 
     */
    public WriteEventLogResponse createWriteEventLogResponse() {
        return new WriteEventLogResponse();
    }

    /**
     * Create an instance of {@link CtModestoWsaWsWriteEventLogResponse }
     * 
     */
    public CtModestoWsaWsWriteEventLogResponse createCtModestoWsaWsWriteEventLogResponse() {
        return new CtModestoWsaWsWriteEventLogResponse();
    }

    /**
     * Create an instance of {@link CreateRmaResponse }
     * 
     */
    public CreateRmaResponse createCreateRmaResponse() {
        return new CreateRmaResponse();
    }

    /**
     * Create an instance of {@link CtModestoWsaWsCreateRmaResponse }
     * 
     */
    public CtModestoWsaWsCreateRmaResponse createCtModestoWsaWsCreateRmaResponse() {
        return new CtModestoWsaWsCreateRmaResponse();
    }

    /**
     * Create an instance of {@link SetRmaStatusResponse }
     * 
     */
    public SetRmaStatusResponse createSetRmaStatusResponse() {
        return new SetRmaStatusResponse();
    }

    /**
     * Create an instance of {@link CtModestoWsaWsSetRmaStatusResponse }
     * 
     */
    public CtModestoWsaWsSetRmaStatusResponse createCtModestoWsaWsSetRmaStatusResponse() {
        return new CtModestoWsaWsSetRmaStatusResponse();
    }

    /**
     * Create an instance of {@link CompleteOrderPaymentResponse }
     * 
     */
    public CompleteOrderPaymentResponse createCompleteOrderPaymentResponse() {
        return new CompleteOrderPaymentResponse();
    }

    /**
     * Create an instance of {@link CtModestoWsaWsCompleteOrderPaymentResponse }
     * 
     */
    public CtModestoWsaWsCompleteOrderPaymentResponse createCtModestoWsaWsCompleteOrderPaymentResponse() {
        return new CtModestoWsaWsCompleteOrderPaymentResponse();
    }

    /**
     * Create an instance of {@link GetInterfaceVersionResponse }
     * 
     */
    public GetInterfaceVersionResponse createGetInterfaceVersionResponse() {
        return new GetInterfaceVersionResponse();
    }

    /**
     * Create an instance of {@link CompleteOrderPayment }
     * 
     */
    public CompleteOrderPayment createCompleteOrderPayment() {
        return new CompleteOrderPayment();
    }

    /**
     * Create an instance of {@link CtModestoWsaWsCompleteOrderPaymentRequest }
     * 
     */
    public CtModestoWsaWsCompleteOrderPaymentRequest createCtModestoWsaWsCompleteOrderPaymentRequest() {
        return new CtModestoWsaWsCompleteOrderPaymentRequest();
    }

    /**
     * Create an instance of {@link DeactivateDeviceResponse }
     * 
     */
    public DeactivateDeviceResponse createDeactivateDeviceResponse() {
        return new DeactivateDeviceResponse();
    }

    /**
     * Create an instance of {@link CtModestoWsaWsDeactivateDeviceResponse }
     * 
     */
    public CtModestoWsaWsDeactivateDeviceResponse createCtModestoWsaWsDeactivateDeviceResponse() {
        return new CtModestoWsaWsDeactivateDeviceResponse();
    }

    /**
     * Create an instance of {@link SetRmaStatus }
     * 
     */
    public SetRmaStatus createSetRmaStatus() {
        return new SetRmaStatus();
    }

    /**
     * Create an instance of {@link CtModestoWsaWsSetRmaStatusRequest }
     * 
     */
    public CtModestoWsaWsSetRmaStatusRequest createCtModestoWsaWsSetRmaStatusRequest() {
        return new CtModestoWsaWsSetRmaStatusRequest();
    }

    /**
     * Create an instance of {@link CtModestoWsaWsOModWsaInvDtl }
     * 
     */
    public CtModestoWsaWsOModWsaInvDtl createCtModestoWsaWsOModWsaInvDtl() {
        return new CtModestoWsaWsOModWsaInvDtl();
    }

    /**
     * Create an instance of {@link CtModestoWsaWsOidvalue }
     * 
     */
    public CtModestoWsaWsOidvalue createCtModestoWsaWsOidvalue() {
        return new CtModestoWsaWsOidvalue();
    }

}
